name: github action start

on:
  push:
    branches:
      - main

jobs:
  my-deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: echo "hello world"

      - name: many sentence
        run: |
          echo "bad"
          echo "bye"

      - name: use variable
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
