name: github action 01111

on:
  push:
    branches:
      - main

jobs:
  my-deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: echo "hell world"

      - name: many sentence
        run: |
          echo "hell"
          echo "hell morning"

      - name: Github Actions
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Print Secrets
        run: |
          echo "${{ secrets.MY_NAME }}"
          echo "${{ secrets.MY_HOBBY }}"
